// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgagvydtistyjwxuxwyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnYWd2eWR0aXN0eWp3eHV4d3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzYxMjEsImV4cCI6MjA1OTgxMjEyMX0.QyvKOP8JZBv6cEUpqAoLvV7uLPBVZo9D5s18I0zCVD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);